=== lbovet/scardif/src/main/resources/person-schema.json
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "Arbitrary label"
      }
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    },
    "recruitment" : {
      "type": "string",
      "format": "date"
    },
    "address": {
      "$ref": "#/definitions/Address"
    },
    "deliveryAddresses": {
      "type" : "array",
      "items" : {
        "$ref": "#/definitions/Address"
      }
    },
    "family": {
      "type": "object",
      "properties": {
        "spouse":  {
          "type": "string"
        }
      }
    }
  },
  "definitions": {
    "Address": {
      "type": "object",
      "properties": {
        "street": {
          "type": "string"
        }
      }
    }
  }
}

=== lbovet/scardif/src/test/resources/john.json
{
  "firstName": "John",
  "lastName": "Doe",
  "age": 21,
  "recruitment": "2020-01-01",
  "tags": [
    "new",
    "good"
  ],
  "address": {
    "street": "Baker St."
  },
  "deliveryAddresses": [
    {
      "street" : "Main St."
    },
    {
      "street" : "Second St."
    }
  ],
  "family": {
    "spouse": "Mary"
  }
}
